/* DO NOT EDIT THIS FILE - it is machine generated */

#include <platform/android/jni/JniHelper.h>

/* Header for class org_cocos2dx_cpp_jniInterface */

#ifndef _Included_org_cocos2dx_cpp_jniInterface
#define _Included_org_cocos2dx_cpp_jniInterface
#ifdef __cplusplus
extern "C" {
#endif

USING_NS_CC;

/*
 * Class:     org_cocos2dx_cpp_jniInterface
 * Method:    setJniInterfaceToDll
 * Signature: (Lorg/cocos2dx/cpp/jniInterface;)V
 */
JNIEXPORT void JNICALL Java_org_cocos2dx_cpp_jniInterface_setJniInterfaceToDll
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     org_cocos2dx_cpp_jniInterface
 * Method:    recieveRomoteData
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_org_cocos2dx_cpp_jniInterface_recieveRomoteData
  (JNIEnv *, jobject, jbyteArray);


JNIEXPORT void JNICALL Java_org_cocos2dx_cpp_jniInterface_payResult(
		JNIEnv *env, jobject obj, jint handleSharkCode , jint result );

jobject getJniObject();

void sendDataToRemote(char* pData, int dataLen);

jint byteToInt(char *bytes, int i);

int getMac( void *env , char mac[40] );

#ifdef __cplusplus
}
#endif
#endif
